#
# 개발 환경 설정 파일
#

spring:
  config:
    activate:
      # 활성화할 프로필 명
      on-profile: dev
  # 데이터베이스 연결 정보 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


server:
  # 서버 포트 번호 변경
  port: 4545

